pipeline {
    agent {
        docker {
            image 'python:2.7.16-slim'
        }
    }

    tools {
        nodejs 'NodeJS 8.9.0'
    }

    stages {
        stage('build') {
            when{
                changeset "**/vote/**"
            }
            steps {
                echo 'Compiling worker app'
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('test') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Running Unit Tests on worker app'
                dir('vote'){
                    sh 'nosetests -v'
                }
            }
        }
    }
}
